# first Github Action workflow!

name: Build Application 

runs:
  using: composite

  steps:
  - name: Checkout repository 
    uses: actions/checkout@v4

  - name: Set up Python 3.13
    uses: actions/setup-python@v5
    with:
      python-version: "3.13"
    
  - name: Install Poetry 
    uses: snok/install-poetry@v1
    with:
      virtualenvs-create: true
      virtualenvs-in-project: true
      installer-parallel: true
  
  - name: Load cached venv
    id: cached-poetry-dependencies
    uses: actions/cache@v3
    with:
      path: .venv
      key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
  
  - name: Install dependencies using poetry 
    if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
    run: poetry run make install 
    shell: bash
    